version: '3'
services:
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      - PORT
      - DATABASE_URL
    container_name: ca-game-api
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - db-test
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    container_name: ca-game-api-db
    tty: true
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dev-data:/var/lib/postgresql/data
      - ./build/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  db-test:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
      POSTGRES_DB: test_db
    container_name: ca-game-api-test-db
    tty: true
    restart: always
    ports:
      - 15432:5432
    volumes:
      - test-data:/var/lib/postgresql/data
      - ./build/setup_test.sql:/docker-entrypoint-initdb.d/setup_test.sql

volumes:
  dev-data:
    driver: local
  test-data:
    driver: local
