version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DRIVER: ${DRIVER}
      DATASOURCE: ${DATASOURCE}
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/github.com/minguu42/ca-game-api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mysql-container
    tty: true
    ports:
      - 3336:3336
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
