version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT
      - DRIVER
      - DATABASE_URL
    container_name: ca-game-api
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.6
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    container_name: ca-game-api-db
    tty: true
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
