version: '3'
services:
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      - PORT
      - DSN
    container_name: ca-game-api
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db-dev
  db-dev:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    container_name: ca-game-api-db-dev
    restart: always
    volumes:
      - data-dev:/var/lib/postgresql/data
      - ./build/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  db-test:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
      POSTGRES_DB: db_test
    container_name: ca-game-api-db-test
    restart: always
    ports:
      - 15432:5432
    volumes:
      - data-test:/var/lib/postgresql/data
  docs:
    image: swaggerapi/swagger-ui
    container_name: ca-game-api-docs
    environment:
      API_URL: openapi.yaml
    ports:
      - 8000:8080
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml

volumes:
  data-dev:
    driver: local
  data-test:
    driver: local
