openapi: 3.0.3

info:
  version: 1.0.0
  title: CA GAME API
  description: |
    ca-game-api の API 仕様です.

    TechTrain のミッションである[オンライン版　CA Tech Dojo サーバサイド (Go)編](https://techbowl.co.jp/techtrain/missions/12)に取り組んだ後に, オリジナル要素を加えて自分で作成したものです.
    ユーザランキング情報取得 API, キャラクター合成 API がオリジナル要素になります.

    [TechTrain MISSION Game API](https://github.com/CyberAgentHack/techtrain-mission/blob/master/api-document.yaml)を元にしています.

servers:
  - description: ローカルサーバ
    url: http://localhost:8080

tags:
  - name: user
    description: ユーザ関連 API
  - name: gacha
    description: ガチャ関連 API
  - name: character
    description: キャラクター関連 API

paths:
  /user/create:
    post:
      summary: ユーザ情報作成 API
      tags: 
        - user
      description: |
        ユーザ情報を作成します.
        ユーザの名前情報をリクエストで受け取り, ユーザIDと認証用トークンを生成し, データベースへ保存します.
        既に使用されているユーザ名では登録できません.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ユーザ名
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: クライアント側で保存するトークン
        "400":
          $ref: "#/components/responses/BadRequest"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
        "409":
          description: ユーザ名が既に使用されている
        "500":
          $ref: "#/components/responses/InternalServerError"
  /user/get:
    get:
      summary: ユーザ情報取得 API
      tags: 
        - user
      description: |
        ユーザ情報を取得します.
        ユーザの認証と特定の処理はリクエストヘッダの x-token を読み取ってデータベースに照会をします.
      parameters:
        - $ref: "#/components/parameters/x-token"
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: ユーザ名
        "401":
          $ref: "#/components/responses/Unauthorized"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /user/update:
    put:
      summary: ユーザ情報更新 API
      tags:
        - user
      description: |
        ユーザ情報を更新します.
        初期実装では名前の更新を行います.
      parameters:
        - $ref: "#/components/parameters/x-token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 新しいユーザ名
      responses:
        '200':
          description: 成功
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
        "409":
          description: ユーザ名が既に使用されている
        "500":
          $ref: "#/components/responses/InternalServerError"
  /user/ranking:
    get:
      summary: ユーザランキング情報取得 API
      tags:
        - user
      description: |
        ユーザのランキング情報を取得します.
        ランキング情報には上位3位までのユーザ情報が含まれます.
      parameters:
        - $ref: "#/components/parameters/x-token"
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  userRanking:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: ユーザ名
                        sumPower:
                          type: integer
                          description: ユーザの所有するキャラクターの合計パワー
        "401":
          $ref: "#/components/responses/Unauthorized"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /gacha/draw:
    post:
      summary: ガチャ実行API
      tags:
        - gacha
      description: |
        ガチャを引いてキャラクターを取得する処理を実装します。
        獲得したキャラクターはユーザ所持キャラクターテーブルへ保存します。
        同じ種類のキャラクターでもユーザは複数所持することができます。
        
        キャラクターの確率は等倍ではなく、任意に変更できるようテーブルを設計しましょう。
      parameters: 
        - name: x-token
          in: header
          required: true
          description: 認証トークン
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                times:
                  type: integer
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        characterID:
                          type: string
                        name:
                          type: string
  /character/list:
    get:
      summary: ユーザ所持キャラクター一覧取得API
      tags:
        - character
      description: |
        ユーザが所持しているキャラクター一覧情報を取得します。
      parameters: 
        - name: x-token
          in: header
          required: true
          description: 認証トークン
          schema:
            type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  characters:
                    type: array
                    items:
                      type: object
                      properties:
                        userCharacterID:
                          type: string
                        characterID:
                          type: string
                        name:
                          type: string
  /character/compose:
    post:
      summary: キャラクター合成 API
      tags:
        - character
      description: |
        所有しているキャラクターを合成し、キャラクターのレベルを上げます。
        
        合成されたキャラクターは失われます。
      parameters:
        - name: x-token
          in: header
          required: true
          description: 認証トークン
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                baseUserCharacterID:
                  type: integer
                materialUserCharacterID:
                  type: integer
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  userCharacterID:
                    type: string
                  characterID:
                    type: string
                  name:
                    type: string
                  level:
                    type: integer

components:
  parameters:
    x-token:
      name: x-token
      description: 認証トークン
      in: header
      required: true
      schema:
        type: string
  responses:
    BadRequest:
      description: リクエストが間違っている
    MethodNotAllowed:
      description: リクエストメソッドが間違っている
    Unauthorized:
      description: ユーザを認証できない
    Forbidden:
      description: リソースへのアクセス権限がない
    InternalServerError:
      description: サーバ側で不明なエラーが発生した
